server:
  port: 80
spring:
  redis:
    database: 0
    host: ${REDIS_SERVICE_HOST:127.0.0.1}
    port: ${REDIS_SERVICE_PORT:6379}
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    timeout: 3000